extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
pipelines:
  overrides:
  - pipeline: pullRequest
    stage: build
    name: npmrc
    steps:
    - sh: jx step credential -s jenkins-npm-token -k file -f /builder/home/.npmrc --optional=true
      name: npmrc
#pipelines:
#  overrides:
#  - pipeline: pullRequest
#    stage build: 
#  pullRequest:
#    build:
#      preSteps:
#      - sh: echo “Ovo su preSteps za PR!”

