extends:
  file: ../javascript/pipeline.yaml
pipelines:
  pullRequest:
    preBuild:
      steps:
        - sh: echo `which pip`
          name: test-pip
  overrides:
    - pipeline: pullRequest
      stage: preBuild
      agent:
        image: "gcr.io/jenkinsxio/jenkins-python:latest"
      steps:
        - sh: echo `which pip`
          name: test-pip
      stage: build