extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
env:
  NPM_LOGIN: jx-npm-user 
  NPM_PASSWORD: tzSyL8Au53NhJAa 
pipelines:
  pullRequest:
    build:
      preSteps:
      - sh: echo “Ovo su preSteps za PR!”

