extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
pipelines:
  overrides:
  - pipeline: pullRequest
#  pullRequest:
#    build:
#      preSteps:
#      - sh: echo “Ovo su preSteps za PR!”

