extends:
  file: ../javascript/pipeline.yaml
pipelines:
  pullRequest:
    preBuild:
      steps:
        - sh: pip install awscli --upgrade --user && ls -la $HOME/.local/bin
          name: pip-install-awscli
        # - sh: aws --help
        #   name: aws-cli-test
  overrides:
    - pipeline: pullRequest
      stage: preBuild
      agent:
        image: "gcr.io/jenkinsxio/jenkins-python:latest"
      stage: build
      stage: postBuild
      stage: promote
