extends:
  file: ../javascript/pipeline.yaml
pipelines:
  pullRequest:
    preBuild:
      steps:
        - sh: pip install awscli --upgrade --user
          name: pip-install-awscli
        - sh: aws --help
          name: aws-cli-test
    build:
      steps:
        - loop:
            variable: OSs
            values:
              - linux
              - windows
            steps:
              - name: build
                command: echo \${GOOS}
  overrides:
    - pipeline: pullRequest
      stage: preBuild
      agent:
        image: "gcr.io/jenkinsxio/jenkins-python:latest"
    - pipeline: pullRequest
      stage: build
    - pipeline: pullRequest
      stage: postBuild
    - pipeline: pullRequest
      stage: promote
