extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
# pipelines:
# overrides:
# - pipeline: pullRequest
# agent:
# image: "gcr.io/jenkinsxio/jenkins-python:latest"
# stage: build
# preSteps:
# - sh: echo `which pip`
# name: npm-test
# steps:
# - sh: jx step credential -s jenkins-npm-token -k file -f /builder/home/.npmrc --optional=true
#   name: npmrc
pipelines:
  overrides:
    - pipeline: pullRequest
      stage preBuild:
      agent:
        image: "gcr.io/jenkinsxio/jenkins-python:latest"
      name: test-python-preBuildStage
      steps:
        - sh: echo `which pip`
          name:
            test pip in preBuild stage
            # preSteps:
            #   - sh: echo “Ovo su preSteps za PR!”
