extends:
  file: ../javascript/pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
env:
  NPM_LOGIN: vault:npm/npm_login
  NPM_PASSWORD: vault:npm/npm_password
pipelines:
  pullRequest:
    build:
      preSteps:
      - sh: echo “Ovo su preSteps za PR!”

